name: relativity_lite_mobile
description: Offline Relativity-lite (import, search, tag, export) – free.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  pdf_text: ^0.7.1
  sqflite: ^2.3.3+1
  sqlite3_flutter_libs: ^0.5.24
  share_plus: ^10.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
